version: '3'
services: 
  wordpress:
    image: wordpress:latest
    volumes:
      - !Ref LeBucket:/var/www/html/wp-content
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: !Ref DatabaseWP.ENDPOINT:3306
      WORDPRESS_DB_USER: !Ref DBUser
      WORDPRESS_DB_PASSWORD: !Ref DBPassword
      WORDPRESS_DB_NAME: !Ref DBNom
