version: '3'
services:
  
  wordpress:
    image: wordpress:latest
    volumes:
      - c:\test\wp-content:/var/www/html/wp-content
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: administrateur
      WORDPRESS_DB_PASSWORD: Marinash-66
      WORDPRESS_DB_NAME: datawp
